int a = 10;
int b = 21;
int c = 6;
int d = 18;
int e = 8;
int max = a;
if (a > max) max = a;
if (b > max) max = b;
if (c > max) max = c;
if (d > max) max = d;
if (e > max) max = e;
Console.Write("Max = ");
Console.WriteLine(max);